#!/bin/bash

# Script để upgrade Node.js từ v12 lên v20
# Created: 2025-12-31

echo "=========================================="
echo "🚀 UPGRADE NODE.JS - HƯỚNG DẪN CHI TIẾT"
echo "=========================================="
echo ""

# Kiểm tra Node.js version hiện tại
CURRENT_NODE=$(node -v 2>/dev/null || echo "not installed")
echo "📌 Node.js hiện tại: $CURRENT_NODE"
echo ""

if [[ $CURRENT_NODE == v12* ]] || [[ $CURRENT_NODE == "not installed" ]]; then
    echo "⚠️  Node.js version này QUÁ CŨ!"
    echo "✅ Cần upgrade lên Node.js v20 trở lên"
    echo ""
    echo "=========================================="
    echo "CÁCH 1: SỬ DỤNG NVM (KHUYẾN NGHỊ) ✨"
    echo "=========================================="
    echo ""
    echo "Bước 1: Cài đặt nvm"
    echo "--------------------"
    echo "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash"
    echo ""
    echo "Bước 2: Load nvm vào shell"
    echo "--------------------------"
    echo "export NVM_DIR=\"\$HOME/.nvm\""
    echo "[ -s \"\$NVM_DIR/nvm.sh\" ] && \\. \"\$NVM_DIR/nvm.sh\""
    echo ""
    echo "source ~/.bashrc  # hoặc source ~/.zshrc"
    echo ""
    echo "Bước 3: Cài Node.js v20"
    echo "-----------------------"
    echo "nvm install 20"
    echo "nvm use 20"
    echo "nvm alias default 20"
    echo ""
    echo "Bước 4: Verify"
    echo "--------------"
    echo "node --version  # Phải hiển thị v20.x.x"
    echo ""
    echo "=========================================="
    echo "CÁCH 2: CÀI TRỰC TIẾP (Ubuntu/Debian)"
    echo "=========================================="
    echo ""
    echo "# Xóa Node.js cũ"
    echo "sudo apt remove nodejs npm"
    echo ""
    echo "# Thêm NodeSource repository"
    echo "curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -"
    echo ""
    echo "# Cài Node.js 20"
    echo "sudo apt-get install -y nodejs"
    echo ""
    echo "# Verify"
    echo "node --version"
    echo ""
    echo "=========================================="
    echo "SAU KHI UPGRADE XONG"
    echo "=========================================="
    echo ""
    echo "cd /home/toan.nguyen10/workspace/learning/javascript_learning"
    echo "npm install  # Cài lại dependencies nếu cần"
    echo "npm run dev  # Chạy app"
    echo ""
    echo "Mở browser: http://localhost:5173"
    echo ""
else
    echo "✅ Node.js version OK!"
    echo ""
    echo "Bạn có thể chạy app ngay:"
    echo "-------------------------"
    echo "cd /home/toan.nguyen10/workspace/learning/javascript_learning"
    echo "npm run dev"
fi

echo ""
echo "=========================================="
echo "📚 Tài liệu hướng dẫn chi tiết:"
echo "   - README.md"
echo "   - INSTALLATION.md"
echo "=========================================="

